[target.aarch_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-Clink-arg=-fuse-ld=lld", # Use LLD Linker
  "-Zshare-generics=y",      # (Nightly) Make the current crate share its generic instantiations
  "-Zthreads=0",             # (Nightly) Use improved multithreading with the recommended amount of threads.
]
