[package]
name = "manoka"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy.workspace = true
bevy-inspector-egui = { version = "0.24" }
bevy_mod_debugdump = "0.10"
wgpu.workspace = true
zerocopy.workspace = true
